### ISSUE TITLE
Modernisation

### ISSUE THREAD

**Issue by sachaw** [ngageoint/mgrs-js#5]
Would there be any interest in migrating this project to more modern tooling and using an ESM only output?

I have a fork of this library: https://github.com/sachaw/mgrs-js/
There are a number of changes that I am implementing:
- Use [Biome](https://biomejs.dev/) in favour of TSLint + Pretter
- Make package pure ESM
- Move testing to a typescript native framework such as [Japa](https://japa.dev/docs/introduction)
- Improve formatting and correctness (semantics)
- Use PNPM over NPM
- Likely more

**Comment by danielbarela** [comment]
Sure, if you want to make some improvements, go for it.  Once you are done you can issue a pull request and we will take a look.

**Comment by danielbarela** [comment]
Except the ESM thing.  We use CommonJS and are not going to switch everything to ESM

**Comment by restjohn** [comment]
Additionally, I don't think we'll be switching our toolchain to PNPM.  You're free to use PNPM if you wish, and make any modifications to satisfy its stricter requirements, but this package won't require it.  I personally don't have a strong opinion on the specific linter.  I question the payoff of switching test frameworks, and we certainly won't embark on that, but as @danielbarela says, we will gladly consider a PR.  Thanks for your interest and contribution.
